-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-07-19 01:56:32 PDT
--   site:      SQL Server 2012
--   type:      SQL Server 2012
--=================================
/*
CREATE DATABASE YAYOBE_AUTO_INSURANCE
GO
--====================================
USE YAYOBE_AUTO_INSURANCE
GO
*/
DROP TABLE IF EXISTS accident_report  ---1
GO

ALTER TABLE policy 
    DROP CONSTRAINT policy_agent_FK 
GO

DROP TABLE IF EXISTS agent ---2
GO

ALTER TABLE accident_report 
    DROP CONSTRAINT accident_report_claim_FK 
GO

DROP TABLE IF EXISTS claim --3
GO

DROP TABLE IF EXISTS coverage --4
GO

ALTER TABLE coverage 
    DROP CONSTRAINT coverage_coverage_type_FK 
GO

DROP TABLE IF EXISTS coverage_type  --5
GO

ALTER TABLE policy 
    DROP CONSTRAINT policy_customer_FK 
GO

ALTER TABLE vehicle  ---6
    DROP CONSTRAINT vehicle_customer_FK 
GO

DROP TABLE IF EXISTS customer  --7
GO

DROP TABLE IF EXISTS payment --8
GO

ALTER TABLE claim 
    DROP CONSTRAINT claim_policy_FK 
GO

ALTER TABLE coverage 
    DROP CONSTRAINT coverage_policy_FK 
GO

ALTER TABLE payment 
    DROP CONSTRAINT payment_policy_FK 
GO

DROP TABLE IF EXISTS policy  ---9
GO

DROP TABLE IF EXISTS vehicle
GO

CREATE TABLE accident_report 
    (
     report_id INTEGER NOT NULL , 
     accident_date DATE , 
     accident_time TIME , 
     location VARCHAR (120) , 
     police_report_number NVARCHAR (120) , 
     fault_determination VARCHAR (120) , 
     claim_claim_id INTEGER NOT NULL 
    )
GO

ALTER TABLE accident_report ADD CONSTRAINT 
accident_report_PK PRIMARY KEY CLUSTERED (report_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE agent 
    (
     agent_id INTEGER NOT NULL , 
     agent_name VARCHAR (120) , 
     agent_address VARCHAR (120) , 
     city VARCHAR (120) , 
     state VARCHAR (120) , 
     zip_code VARCHAR (120) , 
     agent_phone NVARCHAR (120) , 
     agent_email VARCHAR (120) , 
     agent_website VARCHAR (120) , 
     commission_rate NVARCHAR (120) 
    )
GO

ALTER TABLE agent ADD CONSTRAINT 
agent_PK PRIMARY KEY CLUSTERED (agent_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE claim 
    (
     claim_id INTEGER NOT NULL , 
     claim_date DATE , 
     claim_status VARCHAR (120) , 
     "claim-amount" DECIMAL (16,2) , 
     "accident-description" VARCHAR (120) , 
     policy_policy_id INTEGER NOT NULL 
    )
GO

ALTER TABLE claim ADD CONSTRAINT 
claim_PK PRIMARY KEY CLUSTERED (claim_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE coverage 
    (
     coverage_id INTEGER NOT NULL , 
     coverage_type VARCHAR (120) , 
     coverage_limit DECIMAL (16,2) , 
     deductible DECIMAL (16,2) , 
     policy_policy_id INTEGER NOT NULL , 
     coverage_type_type_id INTEGER NOT NULL 
    )
GO

ALTER TABLE coverage ADD CONSTRAINT 
coverage_PK PRIMARY KEY CLUSTERED (coverage_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE coverage_type 
    (
     type_id INTEGER NOT NULL , 
     coverage_name VARCHAR (120) 
    )
GO

ALTER TABLE coverage_type ADD CONSTRAINT 
coverage_type_PK PRIMARY KEY CLUSTERED (type_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE customer 
    (
     customer_id INTEGER NOT NULL , 
     first_name VARCHAR (120) , 
     last_name VARCHAR (120) , 
     "date-of_birth" DATE , 
     age_discription VARCHAR (120) , 
     cust_address VARCHAR (120) , 
     city VARCHAR (120) , 
     state VARCHAR (120) , 
     zip_code VARCHAR (120) , 
     cust_phone NVARCHAR (120) , 
     cust_email NVARCHAR (120) , 
     driver_license_number NVARCHAR (120) , 
     marital_status VARCHAR (120) , 
     occupation VARCHAR (120) , 
     gender VARCHAR (120) , 
     education_level VARCHAR (120) , 
     ssn NVARCHAR (120) 
    )
GO

ALTER TABLE customer ADD CONSTRAINT 
customer_PK PRIMARY KEY CLUSTERED (customer_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE payment 
    (
     payment_id INTEGER NOT NULL , 
     payment_date DATE , 
     payment_amount DECIMAL (16,2) , 
     payment_method VARCHAR (120) , 
     "payment-status" VARCHAR (120) , 
     policy_policy_id INTEGER NOT NULL 
    )
GO

ALTER TABLE payment ADD CONSTRAINT 
payment_PK PRIMARY KEY CLUSTERED (payment_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE policy 
    (
     policy_id INTEGER NOT NULL , 
     policy_number VARCHAR (120) , 
     start_date DATE , 
     end_date DATE , 
     policy_status VARCHAR (120) , 
     premium_amount DECIMAL (16,2) , 
     customer_customer_id INTEGER NOT NULL , 
     agent_agent_id INTEGER NOT NULL 
    )
GO

ALTER TABLE policy ADD CONSTRAINT 
policy_PK PRIMARY KEY CLUSTERED (policy_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE vehicle 
    (
     vehicle_id INTEGER NOT NULL , 
     make VARCHAR (120) , 
     model VARCHAR (120) , 
     color VARCHAR (120) , 
     year INTEGER , 
     vin NVARCHAR (120) , 
     license_plate_number NVARCHAR (120) , 
     state_regesterd VARCHAR (120) , 
     customer_customer_id INTEGER NOT NULL 
    )
GO

ALTER TABLE vehicle ADD CONSTRAINT 
vehicle_PK PRIMARY KEY CLUSTERED (vehicle_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE accident_report 
    ADD CONSTRAINT accident_report_claim_FK FOREIGN KEY 
    ( 
     claim_claim_id
    ) 
    REFERENCES claim 
    ( 
     claim_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE claim 
    ADD CONSTRAINT claim_policy_FK FOREIGN KEY 
    ( 
     policy_policy_id
    ) 
    REFERENCES policy 
    ( 
     policy_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE coverage 
    ADD CONSTRAINT coverage_coverage_type_FK FOREIGN KEY 
    ( 
     coverage_type_type_id
    ) 
    REFERENCES coverage_type 
    ( 
     type_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE coverage 
    ADD CONSTRAINT coverage_policy_FK FOREIGN KEY 
    ( 
     policy_policy_id
    ) 
    REFERENCES policy 
    ( 
     policy_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE payment 
    ADD CONSTRAINT payment_policy_FK FOREIGN KEY 
    ( 
     policy_policy_id
    ) 
    REFERENCES policy 
    ( 
     policy_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE policy 
    ADD CONSTRAINT policy_agent_FK FOREIGN KEY 
    ( 
     agent_agent_id
    ) 
    REFERENCES agent 
    ( 
     agent_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE policy 
    ADD CONSTRAINT policy_customer_FK FOREIGN KEY 
    ( 
     customer_customer_id
    ) 
    REFERENCES customer 
    ( 
     customer_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE vehicle 
    ADD CONSTRAINT vehicle_customer_FK FOREIGN KEY 
    ( 
     customer_customer_id
    ) 
    REFERENCES customer 
    ( 
     customer_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
